//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 01:59:42 PM COT 
//


package com.talosdigital.buyer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.talosdigital.buyer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.talosdigital.buyer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateBuyerResponse }
     * 
     */
    public CreateBuyerResponse createCreateBuyerResponse() {
        return new CreateBuyerResponse();
    }

    /**
     * Create an instance of {@link GetBuyersListReponse }
     * 
     */
    public GetBuyersListReponse createGetBuyersListReponse() {
        return new GetBuyersListReponse();
    }

    /**
     * Create an instance of {@link Buyer }
     * 
     */
    public Buyer createBuyer() {
        return new Buyer();
    }

    /**
     * Create an instance of {@link DeleteBuyerRequest }
     * 
     */
    public DeleteBuyerRequest createDeleteBuyerRequest() {
        return new DeleteBuyerRequest();
    }

    /**
     * Create an instance of {@link GetBuyersListRequest }
     * 
     */
    public GetBuyersListRequest createGetBuyersListRequest() {
        return new GetBuyersListRequest();
    }

    /**
     * Create an instance of {@link CreateBuyerRequest }
     * 
     */
    public CreateBuyerRequest createCreateBuyerRequest() {
        return new CreateBuyerRequest();
    }

    /**
     * Create an instance of {@link GetBuyerResponse }
     * 
     */
    public GetBuyerResponse createGetBuyerResponse() {
        return new GetBuyerResponse();
    }

    /**
     * Create an instance of {@link GetBuyerRequest }
     * 
     */
    public GetBuyerRequest createGetBuyerRequest() {
        return new GetBuyerRequest();
    }

    /**
     * Create an instance of {@link DeleteBuyerResponse }
     * 
     */
    public DeleteBuyerResponse createDeleteBuyerResponse() {
        return new DeleteBuyerResponse();
    }

}
